// Date: 2-4-2013 22:44:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package chessMod.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * MineChess
 * @author MineMaarten
 * www.minemaarten.com
 * @license Lesser GNU Public License v3 (http://www.gnu.org/licenses/lgpl.html)
 * 
 * Models made with Techne, http://techne.zeux.me/Techne
 */

public class ModelQueen extends ModelBase{
    // fields
    ModelRenderer Base1;
    ModelRenderer Base2;
    ModelRenderer Body;
    ModelRenderer Top;
    ModelRenderer Top1;
    ModelRenderer Top2;
    ModelRenderer Body3;
    ModelRenderer Body2;
    ModelRenderer Crown1;
    ModelRenderer Crown2;
    ModelRenderer Crown3;
    ModelRenderer Crown4;
    ModelRenderer Crown5;
    ModelRenderer Crown6;
    ModelRenderer Crown7;
    ModelRenderer Crown8;
    ModelRenderer Crown9;
    ModelRenderer Crown10;
    ModelRenderer Crown11;
    ModelRenderer Crown12;
    ModelRenderer Crown13;
    ModelRenderer Crown14;
    ModelRenderer Crown15;
    ModelRenderer Crown16;
    ModelRenderer Crown17;
    ModelRenderer Crown18;
    ModelRenderer Crown19;
    ModelRenderer Crown20;
    ModelRenderer Crown21;
    ModelRenderer Crown22;

    public ModelQueen(){
        textureWidth = 64;
        textureHeight = 32;

        Base1 = new ModelRenderer(this, 0, 0);
        Base1.addBox(0F, 0F, 0F, 12, 3, 12);
        Base1.setRotationPoint(-6F, 21F, -6F);
        Base1.setTextureSize(64, 32);
        Base1.mirror = true;
        setRotation(Base1, 0F, 0F, 0F);
        Base2 = new ModelRenderer(this, 0, 0);
        Base2.addBox(0F, 0F, 0F, 10, 3, 10);
        Base2.setRotationPoint(-5F, 18F, -5F);
        Base2.setTextureSize(64, 32);
        Base2.mirror = true;
        setRotation(Base2, 0F, 0F, 0F);
        Body = new ModelRenderer(this, 0, 0);
        Body.addBox(0F, 0F, 0F, 8, 3, 8);
        Body.setRotationPoint(-4F, 6F, -4F);
        Body.setTextureSize(64, 32);
        Body.mirror = true;
        setRotation(Body, 0F, 0F, 0F);
        Top = new ModelRenderer(this, 0, 0);
        Top.addBox(0F, 0F, 0F, 10, 2, 10);
        Top.setRotationPoint(-5F, 4F, -5F);
        Top.setTextureSize(64, 32);
        Top.mirror = true;
        setRotation(Top, 0F, 0F, 0F);
        Top1 = new ModelRenderer(this, 0, 0);
        Top1.addBox(0F, 0F, 0F, 4, 3, 4);
        Top1.setRotationPoint(-2F, 1F, -2F);
        Top1.setTextureSize(64, 32);
        Top1.mirror = true;
        setRotation(Top1, 0F, 0F, 0F);
        Top2 = new ModelRenderer(this, 0, 0);
        Top2.addBox(0F, 0F, 0F, 2, 3, 2);
        Top2.setRotationPoint(-1F, -2F, -1F);
        Top2.setTextureSize(64, 32);
        Top2.mirror = true;
        setRotation(Top2, 0F, 0F, 0F);
        Body3 = new ModelRenderer(this, 0, 0);
        Body3.addBox(0F, 0F, 0F, 8, 3, 8);
        Body3.setRotationPoint(-4F, 15F, -4F);
        Body3.setTextureSize(64, 32);
        Body3.mirror = true;
        setRotation(Body3, 0F, 0F, 0F);
        Body2 = new ModelRenderer(this, 0, 0);
        Body2.addBox(1F, 0F, -3F, 6, 6, 6);
        Body2.setRotationPoint(-4F, 9F, 0F);
        Body2.setTextureSize(64, 32);
        Body2.mirror = true;
        setRotation(Body2, 0F, 0F, 0F);
        Crown1 = new ModelRenderer(this, 0, 0);
        Crown1.addBox(0F, 0F, 0F, 1, 2, 1);
        Crown1.setRotationPoint(5F, 2F, -5F);
        Crown1.setTextureSize(64, 32);
        Crown1.mirror = true;
        setRotation(Crown1, 0F, 0F, 0F);
        Crown2 = new ModelRenderer(this, 0, 0);
        Crown2.addBox(0F, 0F, 0F, 1, 3, 1);
        Crown2.setRotationPoint(5F, 1F, -3F);
        Crown2.setTextureSize(64, 32);
        Crown2.mirror = true;
        setRotation(Crown2, 0F, 0F, 0F);
        Crown3 = new ModelRenderer(this, 0, 0);
        Crown3.addBox(0F, 0F, 0F, 1, 4, 1);
        Crown3.setRotationPoint(5F, 0F, -1F);
        Crown3.setTextureSize(64, 32);
        Crown3.mirror = true;
        setRotation(Crown3, 0F, 0F, 0F);
        Crown4 = new ModelRenderer(this, 0, 0);
        Crown4.addBox(0F, 0F, 0F, 1, 4, 1);
        Crown4.setRotationPoint(5F, 0F, 1F);
        Crown4.setTextureSize(64, 32);
        Crown4.mirror = true;
        setRotation(Crown4, 0F, 0F, 0F);
        Crown5 = new ModelRenderer(this, 0, 0);
        Crown5.addBox(0F, 0F, 0F, 1, 3, 1);
        Crown5.setRotationPoint(5F, 1F, 3F);
        Crown5.setTextureSize(64, 32);
        Crown5.mirror = true;
        setRotation(Crown5, 0F, 0F, 0F);
        Crown6 = new ModelRenderer(this, 0, 0);
        Crown6.addBox(0F, 0F, 0F, 1, 2, 1);
        Crown6.setRotationPoint(5F, 2F, 5F);
        Crown6.setTextureSize(64, 32);
        Crown6.mirror = true;
        setRotation(Crown6, 0F, 0F, 0F);
        Crown7 = new ModelRenderer(this, 0, 0);
        Crown7.addBox(0F, 0F, 0F, 1, 4, 1);
        Crown7.setRotationPoint(1F, 0F, 5F);
        Crown7.setTextureSize(64, 32);
        Crown7.mirror = true;
        setRotation(Crown7, 0F, 0F, 0F);
        Crown8 = new ModelRenderer(this, 0, 0);
        Crown8.addBox(0F, 0F, 0F, 1, 3, 1);
        Crown8.setRotationPoint(3F, 1F, 5F);
        Crown8.setTextureSize(64, 32);
        Crown8.mirror = true;
        setRotation(Crown8, 0F, 0F, 0F);
        Crown9 = new ModelRenderer(this, 0, 0);
        Crown9.addBox(0F, 0F, 0F, 1, 4, 1);
        Crown9.setRotationPoint(-1F, 0F, 5F);
        Crown9.setTextureSize(64, 32);
        Crown9.mirror = true;
        setRotation(Crown9, 0F, 0F, 0F);
        Crown10 = new ModelRenderer(this, 0, 0);
        Crown10.addBox(0F, 0F, 0F, 1, 3, 1);
        Crown10.setRotationPoint(-3F, 1F, 5F);
        Crown10.setTextureSize(64, 32);
        Crown10.mirror = true;
        setRotation(Crown10, 0F, 0F, 0F);
        Crown11 = new ModelRenderer(this, 0, 0);
        Crown11.addBox(0F, 0F, 0F, 1, 2, 1);
        Crown11.setRotationPoint(-5F, 2F, 5F);
        Crown11.setTextureSize(64, 32);
        Crown11.mirror = true;
        setRotation(Crown11, 0F, 0F, 0F);
        Crown12 = new ModelRenderer(this, 0, 0);
        Crown12.addBox(0F, 0F, 0F, 1, 2, 1);
        Crown12.setRotationPoint(-6F, 2F, 4F);
        Crown12.setTextureSize(64, 32);
        Crown12.mirror = true;
        setRotation(Crown12, 0F, 0F, 0F);
        Crown13 = new ModelRenderer(this, 0, 0);
        Crown13.addBox(0F, 0F, 0F, 1, 3, 1);
        Crown13.setRotationPoint(-6F, 1F, 2F);
        Crown13.setTextureSize(64, 32);
        Crown13.mirror = true;
        setRotation(Crown13, 0F, 0F, 0F);
        Crown14 = new ModelRenderer(this, 0, 0);
        Crown14.addBox(-7F, 0F, -1F, 1, 4, 1);
        Crown14.setRotationPoint(1F, 0F, 1F);
        Crown14.setTextureSize(64, 32);
        Crown14.mirror = true;
        setRotation(Crown14, 0F, 0F, 0F);
        Crown15 = new ModelRenderer(this, 0, 0);
        Crown15.addBox(0F, 0F, 0F, 1, 4, 1);
        Crown15.setRotationPoint(-6F, 0F, -2F);
        Crown15.setTextureSize(64, 32);
        Crown15.mirror = true;
        setRotation(Crown15, 0F, 0F, 0F);
        Crown16 = new ModelRenderer(this, 0, 0);
        Crown16.addBox(0F, 0F, 0F, 1, 3, 1);
        Crown16.setRotationPoint(-6F, 1F, -4F);
        Crown16.setTextureSize(64, 32);
        Crown16.mirror = true;
        setRotation(Crown16, 0F, 0F, 0F);
        Crown17 = new ModelRenderer(this, 0, 0);
        Crown17.addBox(0F, 0F, 0F, 1, 2, 1);
        Crown17.setRotationPoint(-6F, 2F, -6F);
        Crown17.setTextureSize(64, 32);
        Crown17.mirror = true;
        setRotation(Crown17, 0F, 0F, 0F);
        Crown18 = new ModelRenderer(this, 0, 0);
        Crown18.addBox(0F, 0F, 0F, 1, 2, 1);
        Crown18.setRotationPoint(4F, 2F, -6F);
        Crown18.setTextureSize(64, 32);
        Crown18.mirror = true;
        setRotation(Crown18, 0F, 0F, 0F);
        Crown19 = new ModelRenderer(this, 0, 0);
        Crown19.addBox(0F, 0F, 0F, 1, 3, 1);
        Crown19.setRotationPoint(2F, 1F, -6F);
        Crown19.setTextureSize(64, 32);
        Crown19.mirror = true;
        setRotation(Crown19, 0F, 0F, 0F);
        Crown20 = new ModelRenderer(this, 0, 0);
        Crown20.addBox(0F, 0F, 0F, 1, 3, 1);
        Crown20.setRotationPoint(-4F, 1F, -6F);
        Crown20.setTextureSize(64, 32);
        Crown20.mirror = true;
        setRotation(Crown20, 0F, 0F, 0F);
        Crown21 = new ModelRenderer(this, 0, 0);
        Crown21.addBox(0F, 0F, 0F, 1, 4, 1);
        Crown21.setRotationPoint(0F, 0F, -6F);
        Crown21.setTextureSize(64, 32);
        Crown21.mirror = true;
        setRotation(Crown21, 0F, 0F, 0F);
        Crown22 = new ModelRenderer(this, 0, 0);
        Crown22.addBox(0F, 0F, 0F, 1, 4, 1);
        Crown22.setRotationPoint(-2F, 0F, -6F);
        Crown22.setTextureSize(64, 32);
        Crown22.mirror = true;
        setRotation(Crown22, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5){
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Base1.render(f5);
        Base2.render(f5);
        Body.render(f5);
        Top.render(f5);
        Top1.render(f5);
        Top2.render(f5);
        Body3.render(f5);
        Body2.render(f5);
        Crown1.render(f5);
        Crown2.render(f5);
        Crown3.render(f5);
        Crown4.render(f5);
        Crown5.render(f5);
        Crown6.render(f5);
        Crown7.render(f5);
        Crown8.render(f5);
        Crown9.render(f5);
        Crown10.render(f5);
        Crown11.render(f5);
        Crown12.render(f5);
        Crown13.render(f5);
        Crown14.render(f5);
        Crown15.render(f5);
        Crown16.render(f5);
        Crown17.render(f5);
        Crown18.render(f5);
        Crown19.render(f5);
        Crown20.render(f5);
        Crown21.render(f5);
        Crown22.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z){
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
